//* vamos a mapear la respuesta de la api para poder crear la interface
// Generated by https://quicktype.io

export interface FetchAllPokemonResponse {
    count:    number;
    next:     null;
    previous: null;
    results:  Result[];
}

export interface Result {
    name: string;
    url:  string;
}

export interface Pokemon {
    id: String;
    name: String;
    pic: String;
}
